"""User Motivation Goals

Revision ID: 362e0eca0a77
Revises: db63c9e47010
Create Date: 2025-04-16 17:43:51.227930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362e0eca0a77'
down_revision: Union[str, None] = 'db63c9e47010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_motivations',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('goals', sa.ARRAY(sa.JSON()), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.BigInteger(), nullable=False),
                    sa.Column('updated_at', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_motivations_user_id'), 'user_motivations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_motivations_user_id'), table_name='user_motivations')
    op.drop_table('user_motivations')
    # ### end Alembic commands ###
