"""activities default partition name update

Revision ID: df9980420207
Revises: 54ad936f75da
Create Date: 2024-09-09 17:48:25.596188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9980420207'
down_revision: Union[str, None] = '54ad936f75da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TABLE activitites_default RENAME TO activities_default;"))


def downgrade() -> None:
    op.execute(sa.text("ALTER TABLE activities_default RENAME TO activitites_default;"))
