"""activities partitioned by date

Revision ID: 54ad936f75da
Revises: b70ab50e1bd2
Create Date: 2024-09-04 14:05:50.156460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '54ad936f75da'
down_revision: Union[str, None] = 'b70ab50e1bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the existing 'activities' table if it exists
    op.execute(text("DROP TABLE IF EXISTS activities"))

    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('user_postcode', sa.String(length=10), nullable=False),
    sa.Column('user_age_range', sa.String(length=50), nullable=False),
    sa.Column('minsBrisk', sa.Integer(), nullable=False),
    sa.Column('minsWalking', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('rewards', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'date'),
    postgresql_partition_by='RANGE (date)'
    )
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # ### Create default partition ###
    op.execute(
        text('''CREATE TABLE IF NOT EXISTS activitites_default PARTITION OF activities DEFAULT;''')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
