"""user walking plan

Revision ID: 60c543022791
Revises: f8144e34eabc
Create Date: 2024-08-12 22:05:08.730450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60c543022791"
down_revision: Union[str, None] = "f8144e34eabc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_walking_plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("walking_plan_data", sa.JSON(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_walking_plan_id"), "user_walking_plan", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_walking_plan_user_id"),
        "user_walking_plan",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_walking_plan_user_id"), table_name="user_walking_plan")
    op.drop_index(op.f("ix_user_walking_plan_id"), table_name="user_walking_plan")
    op.drop_table("user_walking_plan")
    # ### end Alembic commands ###
