"""user-authentication-status-and-delete_audit

Revision ID: 7263272bfea3
Revises: 788f862ac2be
Create Date: 2024-08-19 20:54:43.620619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7263272bfea3"
down_revision: Union[str, None] = "788f862ac2be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delete_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("delete_reason", sa.String(length=50), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users", sa.Column("current_token", sa.String(length=500), nullable=True)
    )
    op.add_column("users", sa.Column("status", sa.String(length=10), nullable=True))
    op.add_column("users", sa.Column("status_updated_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_users_current_token"), "users", ["current_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_current_token"), table_name="users")
    op.drop_column("users", "status_updated_at")
    op.drop_column("users", "status")
    op.drop_column("users", "current_token")
    op.drop_table("delete_audit")
    # ### end Alembic commands ###
