"""fk attribute ondelete added _ target updated

Revision ID: 788f862ac2be
Revises: b9643b0c1602
Create Date: 2024-08-15 19:16:36.091338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788f862ac2be'
down_revision: Union[str, None] = 'b9643b0c1602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_user_id_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key('activities_user_id_fkey', 'activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_daily_target', sa.Column('date', sa.Integer(), nullable=True))
    op.drop_index('ix_user_daily_target_user_id', table_name='user_daily_target')
    op.create_index(op.f('ix_user_daily_target_user_id'), 'user_daily_target', ['user_id'], unique=False)
    op.drop_constraint('user_daily_target_user_id_fkey', 'user_daily_target', type_='foreignkey')
    op.create_foreign_key('user_daily_target_user_id_fkey', 'user_daily_target', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_walking_plan_user_id_fkey', 'user_walking_plan', type_='foreignkey')
    op.create_foreign_key('user_walking_plan_user_id_fkey', 'user_walking_plan', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_walking_plan_user_id_fkey', 'user_walking_plan', type_='foreignkey')
    op.create_foreign_key('user_walking_plan_user_id_fkey', 'user_walking_plan', 'users', ['user_id'], ['id'])
    op.drop_constraint('user_daily_target_user_id_fkey', 'user_daily_target', type_='foreignkey')
    op.create_foreign_key('user_daily_target_user_id_fkey', 'user_daily_target', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_daily_target_user_id'), table_name='user_daily_target')
    op.create_index('ix_user_daily_target_user_id', 'user_daily_target', ['user_id'], unique=True)
    op.drop_column('user_daily_target', 'date')
    op.drop_constraint('activities_user_id_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key('activities_user_id_fkey', 'activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
