"""activity_data type correction

Revision ID: 89c973ee4474
Revises: 64189cfb3dc7
Create Date: 2024-07-26 11:54:41.445972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89c973ee4474'
down_revision: Union[str, None] = '64189cfb3dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'activity_date',
               existing_type=mysql.INTEGER(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'activity_date',
               existing_type=sa.DATE(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
