"""user token management

Revision ID: 98c4905bc4df
Revises: 7263272bfea3
Create Date: 2024-08-20 16:57:46.849968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98c4905bc4df"
down_revision: Union[str, None] = "7263272bfea3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_tokens_user_id"), "user_tokens", ["user_id"], unique=False
    )

    # If necessary, you can drop the following lines if not required.
    op.drop_index("ix_users_current_token", table_name="users")
    op.drop_column("users", "current_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "current_token", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_users_current_token", "users", ["current_token"], unique=False)
    op.drop_index(op.f("ix_user_tokens_user_id"), table_name="user_tokens")
    op.drop_table("user_tokens")
    # ### end Alembic commands ###
