"""create scheduled_batches table

Revision ID: aa8451fd521c
Revises: c997a5bc5c1d
Create Date: 2024-09-18 19:59:44.850258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8451fd521c'
down_revision: Union[str, None] = 'c997a5bc5c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_batches',
                    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
                    sa.Column('batch_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('status', sa.String(length=10), nullable=False, server_default='scheduled'),
                    sa.Column('batch_data', sa.JSON(), nullable=False, server_default='{}'),
                    sa.Column('processed_at', sa.DateTime(), nullable=True, server_default=None),
                    sa.Column('batch_size', sa.Integer(), nullable=False),
                    sa.Column('scheduled_time', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
                    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
                    sa.Column(
                        'updated_at', sa.DateTime(), nullable=False,
                        server_default=sa.text('CURRENT_TIMESTAMP'), onupdate=sa.text('CURRENT_TIMESTAMP')
                    ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_batches_batch_id'), 'scheduled_batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_scheduled_batches_id'), 'scheduled_batches', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_batches_scheduled_time'), 'scheduled_batches', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_scheduled_batches_status'), 'scheduled_batches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_batches_status'), table_name='scheduled_batches')
    op.drop_index(op.f('ix_scheduled_batches_scheduled_time'), table_name='scheduled_batches')
    op.drop_index(op.f('ix_scheduled_batches_id'), table_name='scheduled_batches')
    op.drop_index(op.f('ix_scheduled_batches_batch_id'), table_name='scheduled_batches')
    op.drop_table('scheduled_batches')
    # ### end Alembic commands ###
