"""user activity level

Revision ID: b33e91c25011
Revises: 362e0eca0a77
Create Date: 2025-04-17 14:32:36.726775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b33e91c25011'
down_revision: Union[str, None] = '362e0eca0a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_level',
    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_level_id'), 'user_activity_level', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_level_user_id'), 'user_activity_level', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activity_level_user_id'), table_name='user_activity_level')
    op.drop_index(op.f('ix_user_activity_level_id'), table_name='user_activity_level')
    op.drop_table('user_activity_level')
    # ### end Alembic commands ###
