"""user daily target

Revision ID: b9643b0c1602
Revises: 60c543022791
Create Date: 2024-08-13 16:31:26.217513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9643b0c1602'
down_revision: Union[str, None] = '60c543022791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_target',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('daily_target', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_daily_target_id'), 'user_daily_target', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_target_user_id'), 'user_daily_target', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_target_user_id'), table_name='user_daily_target')
    op.drop_index(op.f('ix_user_daily_target_id'), table_name='user_daily_target')
    op.drop_table('user_daily_target')
    # ### end Alembic commands ###
