"""Rename some activities table columns

Revision ID: c997a5bc5c1d
Revises: df9980420207
Create Date: 2024-09-12 18:25:02.769202

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c997a5bc5c1d"
down_revision: Union[str, None] = "df9980420207"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("activities", "minsBrisk", new_column_name="brisk_minutes")
    op.alter_column("activities", "minsWalking", new_column_name="walking_minutes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("activities", "brisk_minutes", new_column_name="minsBrisk")
    op.alter_column("activities", "walking_minutes", new_column_name="minsWalking")
    # ### end Alembic commands ###
