"""Email Notification Logs

Revision ID: db63c9e47010
Revises: 6342e38b112b
Create Date: 2024-10-23 20:23:02.171177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db63c9e47010'
down_revision: Union[str, None] = '6342e38b112b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logout_user_email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=False),
    sa.Column('notification_type', sa.Enum('Logged Out for 6 Months', 'Logged Out for 9 Months', 'Logged Out for 51 Weeks', 'Logged Out for 1 Year', name='notification_type_enum'), nullable=False),
    sa.Column('email_delivery_status', sa.Enum('Sent', 'Failed', name='email_status_enum'), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logout_user_email_logs_email_delivery_status'), 'logout_user_email_logs', ['email_delivery_status'], unique=False)
    op.create_index(op.f('ix_logout_user_email_logs_notification_type'), 'logout_user_email_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_logout_user_email_logs_timestamp'), 'logout_user_email_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logout_user_email_logs_user_email'), 'logout_user_email_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_logout_user_email_logs_user_id'), 'logout_user_email_logs', ['user_id'], unique=False)
    op.create_table('monthly_report_email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('report_month', sa.String(length=12), nullable=False),
    sa.Column('email_delivery_status', sa.Enum('Sent', 'Failed', name='report_email_status_enum'), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_report_email_logs_batch_id'), 'monthly_report_email_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_monthly_report_email_logs_email_delivery_status'), 'monthly_report_email_logs', ['email_delivery_status'], unique=False)
    op.create_index(op.f('ix_monthly_report_email_logs_report_month'), 'monthly_report_email_logs', ['report_month'], unique=False)
    op.create_index(op.f('ix_monthly_report_email_logs_timestamp'), 'monthly_report_email_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_monthly_report_email_logs_user_email'), 'monthly_report_email_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_monthly_report_email_logs_user_id'), 'monthly_report_email_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_report_email_logs_user_id'), table_name='monthly_report_email_logs')
    op.drop_index(op.f('ix_monthly_report_email_logs_user_email'), table_name='monthly_report_email_logs')
    op.drop_index(op.f('ix_monthly_report_email_logs_timestamp'), table_name='monthly_report_email_logs')
    op.drop_index(op.f('ix_monthly_report_email_logs_report_month'), table_name='monthly_report_email_logs')
    op.drop_index(op.f('ix_monthly_report_email_logs_email_delivery_status'), table_name='monthly_report_email_logs')
    op.drop_index(op.f('ix_monthly_report_email_logs_batch_id'), table_name='monthly_report_email_logs')
    op.drop_table('monthly_report_email_logs')
    op.drop_index(op.f('ix_logout_user_email_logs_user_id'), table_name='logout_user_email_logs')
    op.drop_index(op.f('ix_logout_user_email_logs_user_email'), table_name='logout_user_email_logs')
    op.drop_index(op.f('ix_logout_user_email_logs_timestamp'), table_name='logout_user_email_logs')
    op.drop_index(op.f('ix_logout_user_email_logs_notification_type'), table_name='logout_user_email_logs')
    op.drop_index(op.f('ix_logout_user_email_logs_email_delivery_status'), table_name='logout_user_email_logs')
    op.drop_table('logout_user_email_logs')
    op.execute('DROP TYPE IF EXISTS email_status_enum')
    op.execute('DROP TYPE IF EXISTS notification_type_enum')
    op.execute('DROP TYPE IF EXISTS report_email_status_enum')
    # ### end Alembic commands ###
