"""initial migrations

Revision ID: f8144e34eabc
Revises:
Create Date: 2024-08-06 17:13:18.554637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8144e34eabc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("unique_id", sa.String(length=50), nullable=False),
        sa.Column("nhs_number", sa.String(length=10), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=6), nullable=False),
        sa.Column("postcode", sa.String(length=10), nullable=True),
        sa.Column("identity_level", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_unique_id"), "users", ["unique_id"], unique=True)
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mins_brisk", sa.Integer(), nullable=True),
        sa.Column("mins_walking", sa.Integer(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("activity_date", sa.DATE(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activities")
    op.drop_index(op.f("ix_users_unique_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
